version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app   # for local dev hot reload
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # for local dev hot reload
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000  # frontend talks to backend
    depends_on:
      - backend
